domain: robertrigo.github.io
url: https://robertrigo.github.io 

theme: null

sass:
  sass_dir: _sass
  style: compressed
  
collections_dir: dnd

collections:
  Classes:
    output: true
  subclass:
    output: false
  Folk:
    output: true
    
defaults:
  - scope:
      path: ""
      type: "Classes"
    values:
      layout: "class"
  - scope:
      path: ""
      type: "Folk"
    values:
      layout: "folk"
  - scope:
      path: ""
    values:
      layout: "default"